{
	"File": {
		"__typename": "FileMatch",
		"repository": {
			"name": "github.com/AntelopeIO/leap"
		},
		"file": {
			"name": "trace_api.swagger.yaml",
			"size": 0,
			"path": "plugins/trace_api_plugin/trace_api.swagger.yaml",
			"byteSize": 7292,
			"content": "openapi: 3.0.0\ninfo:\n  title: Trace API\n  description: Nodeos Trace API Specification. See developer documentation at https://docs.eosnetwork.com for information on enabling this plugin.\n  version: 1.0.0\n  license:\n    name: MIT\n    url: https://opensource.org/licenses/MIT\n  contact:\n    url: https://eosnetwork.com\nservers:\n  - url: '{protocol}://{host}:{port}/v1/'\n    variables:\n      protocol:\n        enum:\n          - http\n          - https\n        default: http\n      host:\n        default: localhost\n      port:\n        default: \"8080\"\ncomponents:\n  schemas: {}\nsecurity:\n  - {}\npaths:\n  /trace_api/get_block:\n    post:\n      summary: get block\n      description: Returns a block trace object containing retired actions and related metadata.\n      operationId: get_block\n      requestBody:\n        content:\n          application/json:\n            schema:\n              type: object\n              required:\n                - block_num\n              properties:\n                block_num:\n                  type: integer\n                  description: Provide a `block number`\n      responses:\n        \"200\":\n          description: OK - valid response payload\n          content:\n            application/json:\n              schema:\n                oneOf:\n                  - $ref: \"https://docs.eosnetwork.com/openapi/v2.0/BlockTraceV0.yaml\"\n                  - $ref: \"https://docs.eosnetwork.com/openapi/v2.0/BlockTraceV1.yaml\"\n                  - $ref: \"https://docs.eosnetwork.com/openapi/v2.0/BlockTraceV2.yaml\"\n        \"400\":\n          description: Error - requested block number is invalid (not a number, larger than max int)\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  code:\n                    type: integer\n                    example: 400\n                  message:\n                    type: string\n                    example: \"bad or missing block_num\"\n                  error:\n                    $ref: \"#/component/schema/ERROR_DETAILS\"\n        \"404\":\n          description: Error - requested data not present on node\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  code:\n                    type: integer\n                    example: 400\n                  message:\n                    type: string\n                    example: \"bad or missing block_num\"\n                  error:\n                    $ref: \"#/component/schema/ERROR_DETAILS\"\n        \"500\":\n          description: Error - exceptional condition while processing get_block; e.g. corrupt files\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  code:\n                    type: integer\n                    example: 500\n                  message:\n                    type: string\n                    example: \"Trace API encountered an Error which it cannot recover from.  Please resolve the error and relaunch the process\"\n                  error:\n                    $ref: \"#/component/schema/ERROR_DETAILS\"\n\n  /trace_api/get_transaction_trace:\n    post:\n      summary: transaction trace\n      description: Does a scan of the trace files looking for the transaction\n      optionationId: get_transaction_trace\n      requestBody:\n        content:\n          application/json:\n            schema:\n              type: object\n              required:\n                - id\n              properties:\n                id:\n                  type: integer\n                  description: Proviade a transaction id\n      responses:\n        \"200\":\n          content:\n            application/json:\n              schema:\n                oneOf:\n                  - $ref: \"https://docs.eosnetwork.com/openapi/v2.0/TransactionTraceV0.yaml\"\n                  - $ref: \"https://docs.eosnetwork.com/openapi/v2.0/TransactionTraceV1.yaml\"\n                  - $ref: \"https://docs.eosnetwork.com/openapi/v2.0/TransactionTraceV2.yaml\"\n                  - $ref: \"https://docs.eosnetwork.com/openapi/v2.0/TransactionTraceV3.yaml\"\n        \"400\":\n          description: Error - requested block number is invalid (not a number, larger than max int)\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  code:\n                    type: integer\n                    example: 400\n                  message:\n                    type: string\n                    example: \"bad or missing block_num\"\n                  error:\n                    $ref: \"#/component/schema/ERROR_DETAILS\"\n        \"404\":\n          description: Error - requested data not present on node\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  code:\n                    type: integer\n                    example: 400\n                  message:\n                    type: string\n                    example: \"bad or missing block_num\"\n                  error:\n                    $ref: \"#/component/schema/ERROR_DETAILS\"\n        \"500\":\n          description: Error - exceptional condition while processing get_block; e.g. corrupt files\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  code:\n                    type: integer\n                    example: 500\n                  message:\n                    type: string\n                    example: \"Trace API encountered an Error which it cannot recover from.  Please resolve the error and relaunch the process\"\n                  error:\n                    $ref: \"#/component/schema/ERROR_DETAILS\"\ncomponent:\n  schema:\n    TRACE:\n      type: object\n      properties:\n        global_squence:\n          type: integer\n          example: 669\n        receiver:\n          type: string\n          example: myproducer\n        account:\n          type: string\n          example: esio.token\n        action:\n          type: string\n          example: transfer\n        authorization:\n          type: array\n          items:\n            type: object\n            properties:\n              account:\n                type: string\n                example: myaccount\n              permission:\n                type: string\n                example: active\n        data:\n          type: string\n          $ref: \"https://docs.eosnetwork.com/openapi/v2.0/Sha256.yaml\"\n        return_value:\n          type: string\n          example: \"\"\n        params:\n          type: object\n          properties:\n            from:\n              type: string\n              example: eosio\n            to:\n              type: string\n              example: myproducer\n            quantity:\n              type: string\n              example: \"10.000 SYS\"\n            memo:\n              type: string\n              example: \"first transfer\"\n    ERROR_DETAILS:\n      type: object\n      properties:\n        code:\n          type: integer\n          example: 0\n        name:\n          type: string\n        what:\n          type: string\n        details:\n          type: array\n        items:\n          type: string\n",
			"canonicalURL": "/github.com/AntelopeIO/leap@7c534bf3af3852d43be2256366cc1b9ea8e50ce0/-/blob/plugins/trace_api_plugin/trace_api.swagger.yaml",
			"externalURLs": [
				{
					"url": "https://github.com/AntelopeIO/leap/blob/7c534bf3af3852d43be2256366cc1b9ea8e50ce0/plugins/trace_api_plugin/trace_api.swagger.yaml",
					"serviceKind": "GITHUB"
				}
			]
		}
	},
	"Error": "parse: parse spec: parse path items: path \"/trace_api/get_block\": post: operation \"get_block\": responses: 200: content: application/json: schema: parse schema: oneOf: at plugins/trace_api_plugin/trace_api.swagger.yaml:51:27: $ref: resolve \"https://docs.eosnetwork.com/openapi/v2.0/BlockTraceV0.yaml\": get \"https://docs.eosnetwork.com/openapi/v2.0/BlockTraceV0.yaml\": https: do: Get \"https://docs.eosnetwork.com/openapi/v2.0/BlockTraceV0.yaml\": host \"docs.eosnetwork.com\" is not allowed"
}